### ISSUE TITLE
Support iPhone 13

### ISSUE THREAD

**Issue by kentomiya89** [kyle-seongwoo-jun/flutter_apple_product_name#1]
iPhone 13 series not listed, needs to be added

* iPhone 13 mini  
* iPhone 13 
* iPhone 13 Pro 
* iPhone 13 Pro Max

**Comment by kyle-seongwoo-jun** [comment]
Hi @kentomiya89

I just added new models and released 1.1.0 version. Please check it out.

Thank you!

**Comment by kentomiya89** [comment]
@kyle-seongwoo-jun 

Thank you!!

I'm finding this package handy!
