### ISSUE TITLE
Adapt for device_info_plus 10.x.x

### ISSUE THREAD

**Issue by jtreitz** [kyle-seongwoo-jun/flutter_apple_product_name#18]
> every version of apple_product_name requires device_info_plus >=1.0.0 <5.0.0 or ^8.0.0 or ^9.0.0.

https://pub.dev/packages/device_info_plus/changelog

**Comment by jtreitz** [comment]
Thanks for the quick response

**Comment by kentomiya89** [comment]
@kyle-seongwoo-jun @jtreitz 

Thank you!!
For Privacy Manifests, I wanted to update device_info_plus to version 10.x.x! 🙏
