### ISSUE TITLE
Please update device_info_plus

### ISSUE THREAD

**Issue by motucraft** [kyle-seongwoo-jun/flutter_apple_product_name#2]
Could you please update the version of device_info_plus?
https://pub.dev/packages/device_info_plus/changelog

Thanks for the useful package.

**Comment by kyle-seongwoo-jun** [comment]
Hi, @motucraft. Thank you for reporting this issue.

I just fixed and published 1.3.0. Please check it out!

Happy coding 😄

**Comment by motucraft** [comment]
@kyle-seongwoo-jun 
Thank you for your work. I really appreciate it.
